FROM debian:8

# COPY . .

# RUN apt-get update -y && apt-get upgrade -y && apt-get dist-upgrade -y
# RUN apt-get install -y php5

RUN apt-get update -y && apt-get upgrade -y && apt-get dist-upgrade -y
RUN apt-get install -y php5

COPY . .