# Solution
version: '3'
services:
  web:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .

    # Mapping of container port to host
    ports:
      - "5000:5000"
    # Mount volumes
    volumes:
      - ".:/exercise_3"

    # Link database container to app container for reachability
    links:
      - "database:exercisedb"
    
    command: ["flask", "run"]
      
    environment:
      - "FLASK_RUN_HOST=0.0.0.0"
    
  database:

    # Image to fetch from docker hub
    build:
      context: ./db
      dockerfile: Dockerfile-db

    # Environment variables for startup script
    # container will use these variables
    # to start the container with these define variables. 
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=testuser"
      - "MYSQL_PASSWORD=admin123"
      - "MYSQL_DATABASE=backend"
      
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"