version: "3.9"
services:
  web:
    build: .
    tty: true
    ports:
      - "8000:8000"

    command: ["node", "index.js"]

  db:
    image: postgres
    ports:
      - "8001:5432"

    environment:
      - "POSTGRES_PASSWORD=testuser"
      - "POSTGRES_HOST_AUTH_METHOD=trust"